In [39]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hackerearth-ml-solving-the-citizens-grievances/dataset/sample_submission.csv
/kaggle/input/hackerearth-ml-solving-the-citizens-grievances/dataset/train.csv
/kaggle/input/hackerearth-ml-solving-the-citizens-grievances/dataset/test.csv

In [40]:
train = pd.read_csv('../input/hackerearth-ml-solving-the-citizens-grievances/dataset/train.csv')
train

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (16,17,18,19,20,22,23,24,25,26,27,28,45,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,appno,application,country.alpha2,country.name,decisiondate,docname,doctypebranch,ecli,introductiondate,issue.0,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,MS WORD,ru,Russian Federation,NaN,CASE OF KOKOSHKINA v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,MS WORD,tr,Turkey,NaN,CASE OF ÖZCAN v. TURKEY,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,MS WORD,si,Slovenia,NaN,CASE OF DANIJEL PEČNIK v. SLOVENIA,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,MS WORD,ch,Switzerland,NaN,CASE OF PALANCI v. SWITZERLAND,CHAMBER,ECLI:CE:ECHR:2014:0325JUD000260708,NaN,NaN,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,MS WORD,ru,Russian Federation,NaN,CASE OF AMANAT ILYASOVA AND OTHERS v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:1001JUD002700106,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8873,60085/12,MS WORD,ua,Ukraine,NaN,CASE OF RASHITOV AND OTHERS v. UKRAINE,COMMITTEE,ECLI:CE:ECHR:2018:0329JUD006008512,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
8874,19857/09,MS WORD,ru,Russian Federation,NaN,CASE OF URMANOV v. RUSSIA,COMMITTEE,ECLI:CE:ECHR:2016:1011JUD001985709,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8875,67253/01,MS WORD,ru,Russian Federation,NaN,CASE OF BABUSHKIN v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2007:1018JUD006725301,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8876,26737/95,MS WORD,es,Spain,NaN,CASE OF BRUALLA GÓMEZ DE LA TORRE v. SPAIN,CHAMBER,ECLI:CE:ECHR:1997:1219JUD002673795,NaN,"Leases of Urban Property Act, section 135, as ...",...,-1,0,0,0,0,0,0,0,0,3
8877,21695/05,MS WORD,pl,Poland,NaN,CASE OF TUR v. POLAND,CHAMBER,ECLI:CE:ECHR:2007:1023JUD002169505,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4

In [41]:
train['sharepointid'].apply(lambda x: str(x)[:3])
train['sharepointid']

0       349418
1       476616
2       373194
3       392525
4       423100
         ...
8873    473530
8874    456937
8875    340823
8876    443927
8877    343850
Name: sharepointid, Length: 8878, dtype: int64

***Dropping unwanted features***

In [42]:
train = train.drop(['decisiondate','application','docname','ecli','introductiondate','country.name','itemid','languageisocode','originatingbody_type','originatingbody_name','sharepointid','documentcollectionid=CASELAW' ,'documentcollectionid=JUDGMENTS','documentcollectionid=CHAMBER','documentcollectionid=ENG','documentcollectionid=COMMITTEE','documentcollectionid=GRANDCHAMBER','typedescription'],axis = 1)

In [43]:
test = pd.read_csv('../input/hackerearth-ml-solving-the-citizens-grievances/dataset/test.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (14,15,16,17,18,19,20,22,23,24,25,49,50,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [44]:
test = test.drop(['decisiondate','application','docname','ecli','introductiondate','country.name','itemid','languageisocode','originatingbody_type','originatingbody_name','sharepointid','documentcollectionid=CASELAW' ,'documentcollectionid=JUDGMENTS','documentcollectionid=CHAMBER','documentcollectionid=ENG','documentcollectionid=COMMITTEE','documentcollectionid=GRANDCHAMBER','typedescription'],axis = 1)

In [45]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
train['country.alpha2']= label_encoder.fit_transform(train['country.alpha2']) 
test['country.alpha2']= label_encoder.transform(test['country.alpha2'])

***Encoding some feature values***

In [46]:
db=pd.get_dummies(train['doctypebranch'],drop_first=True)
db.head()

   COMMITTEE  GRANDCHAMBER
0          0             0
1          1             0
2          0             0
3          0             0
4          0             0

In [47]:
db=pd.get_dummies(test['doctypebranch'],drop_first=True)
db.head()

   COMMITTEE  GRANDCHAMBER
0          1             0
1          0             0
2          1             0
3          0             0
4          0             0

In [48]:
train=pd.concat([train,db],axis=1)

In [49]:
test=pd.concat([test,db],axis=1)

In [50]:
train = train.drop(['doctypebranch'],axis=1)
test = test.drop(['doctypebranch'],axis=1)

In [51]:
cols = [c for c in train.columns if c.lower()[:5] != 'issue']

In [52]:
train = train[cols]

***Dropping issue , parties , respondent columns***

In [53]:
col = [c for c in test.columns if c.lower()[:5] != 'issue']
test = test[col]

In [54]:
cols = [c for c in train.columns if c.lower()[:7] != 'parties']
train = train[cols]

In [55]:
col = [c for c in test.columns if c.lower()[:7] != 'parties']
test = test[col]

In [56]:
cols = [c for c in train.columns if c.lower()[:10] != 'respondent']
train = train[cols]

In [57]:
col = [c for c in test.columns if c.lower()[:10] != 'respondent']
test = test[col]

***Splitting judgementdate feature into 3 features of day,month,year***

In [58]:
train['judgementdate'] = pd.to_datetime(train['judgementdate'])
train = train.assign(
               day=train.judgementdate.dt.day,
               month=train.judgementdate.dt.month,
               year=train.judgementdate.dt.year)
train.head()
train = train.drop(['judgementdate'],axis = 1)

In [59]:
test['judgementdate'] = pd.to_datetime(test['judgementdate'])
test = test.assign(
               day=test.judgementdate.dt.day,
               month=test.judgementdate.dt.month,
               year=test.judgementdate.dt.year)
test.head()
test = test.drop(['judgementdate'],axis = 1)

In [60]:
train['kpdate'] = pd.to_datetime(train['kpdate'])
train = train.assign(
               day_k=train.kpdate.dt.day,
               month_k=train.kpdate.dt.month,
               year_k=train.kpdate.dt.year)
train.head()
train = train.drop(['kpdate'],axis = 1)

In [61]:
test['kpdate'] = pd.to_datetime(test['kpdate'])
test = test.assign(
               day_k=test.kpdate.dt.day,
               month_k=test.kpdate.dt.month,
               year_k=test.kpdate.dt.year)
test.head()
test = test.drop(['kpdate'],axis = 1)

In [62]:
so=pd.get_dummies(train['separateopinion'],drop_first=True)
so.head()

   True
0     0
1     0
2     1
3     1
4     0

In [63]:
train = train.drop(['separateopinion'],axis=1)

In [64]:
train=pd.concat([train,so],axis=1)

In [65]:
so=pd.get_dummies(test['separateopinion'],drop_first=True)

In [66]:
test = test.drop(['separateopinion'],axis=1)

In [67]:
test=pd.concat([test,so],axis=1)

In [68]:
train

,appno,country.alpha2,originatingbody,rank,article=3,article=6,article=P1,article=5,article=8,article=13,...,importance,COMMITTEE,GRANDCHAMBER,day,month,year,day_k,month_k,year_k,True
0,2052/08,39,4,685.417419,1,0,0,1,0,0,...,4,1.0,0.0,28,5,2009,28,5,2009,0
1,4728/07,44,26,2641.901855,0,0,0,1,0,0,...,4,0.0,0.0,7,10,2018,7,10,2018,0
2,44135/06,41,23,942.213440,0,1,0,0,0,1,...,4,1.0,0.0,18,10,2012,18,10,2012,1
3,2607/08,8,5,1121.770142,0,0,0,0,1,0,...,4,0.0,0.0,25,3,2014,25,3,2014,1
4,27001/06,39,4,704.821594,1,0,0,1,0,1,...,4,0.0,0.0,10,1,2009,10,1,2009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8873,60085/12,45,29,2424.463379,0,1,0,0,0,1,...,4,NaN,NaN,29,3,2018,29,3,2018,0
8874,19857/09,39,27,1698.433228,0,0,0,1,0,0,...,4,NaN,NaN,10,11,2016,10,11,2016,0
8875,67253/01,39,6,607.506531,1,0,0,0,0,0,...,4,NaN,NaN,18,10,2007,18,10,2007,0
8876,26737/95,14,9,362.514832,0,1,0,0,0,0,...,3,NaN,NaN,19,12,1997,19,12,1997,0
8877,21695/05,35,7,608.091614,0,1,0,0,0,1,...,4,NaN,NaN,23,10,2007,23,10,2007,0

In [69]:
train_y = train['importance']

In [70]:
train_x = train.drop(['appno' ,'importance' ],axis=1)

***HyperParameter Tunning***

Most of the time in an unbiased dataset, xgboost works well.
You can try SMOTEboost or Catboost techniques also.

In [76]:
params={
 "learning_rate"    : [ 0.10, 0.15, 0.20] ,
 "max_depth"        : [ 5, 6, 7 ,8],
 "min_child_weight" : [ 1, 3, 5 ],
 "gamma"            : [ 0.0, 0.1, 0.2],
 "colsample_bytree" : [ 0.3, 0.4, 0.5],  
}

In [77]:
## Hyperparameter optimization using RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import xgboost
from sklearn.metrics import precision_score,recall_score,accuracy_score,f1_score,roc_auc_score

In [78]:
classifier=xgboost.XGBClassifier(n_estimators = 1000,nthread=1,objective = 'binary:logistic')

In [79]:
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='accuracy',n_jobs=4,cv=5,verbose=3)

In [80]:
random_search.fit(train_x, train_y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  25 out of  25 | elapsed: 24.0min finished

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, gamma=None,
                                           gpu_id=None, importance_type='gain',
                                           interaction_constraints=None,
                                           learning_rate=None,
                                           max_delta_step=None, max_depth=None,
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           n_estimators=1000...
                                           nthread=1, num_parallel_tree=None,
                                           random_state=None, reg_alpha=None,
                                           reg_lambda=None,
                                           scale_pos_weight=None,
                                           subsample=None, tree_method=None,
                                           validate_parameters=None,
                                           verbosity=None),
                   n_iter=5, n_jobs=4,
                   param_distributions={'colsample_bytree': [0.3, 0.4, 0.5],
                                        'gamma': [0.0, 0.1, 0.2],
                                        'learning_rate': [0.1, 0.15, 0.2],
                                        'max_depth': [5, 6, 7, 8],
                                        'min_child_weight': [1, 3, 5]},
                   scoring='accuracy', verbose=3)

In [81]:
random_search.best_params_

{'min_child_weight': 1,
 'max_depth': 7,
 'learning_rate': 0.15,
 'gamma': 0.1,
 'colsample_bytree': 0.4}

In [82]:
idno = test['appno']

In [83]:
test = test.drop(['appno'],axis=1)

In [84]:
pred = random_search.predict(test)

In [85]:
pred

array([4, 4, 4, ..., 4, 4, 4])

In [86]:
df = pd.DataFrame()

In [87]:
df['appno'] = idno

In [89]:
df['importance'] = pred

In [90]:
df

         appno  importance
0      1194/04           4
1     53865/11           4
2     43838/07           4
3     11157/04           3
4     42443/02           3
...        ...         ...
4755   4345/06           4
4756  10761/09           4
4757    805/09           4
4758  44711/16           4
4759  21155/18           4

[4760 rows x 2 columns]

In [ ]:
df.to_csv('file.csv',index=False)

***If you like the notebook please drop a like***